jobname: 8.2ka
queue: normal
walltime: 3:10:00

# note: if laboratory is relative path, it is relative to /scratch/$PROJECT/$USER
laboratory: /g/data/ob22/yd3797/access-esm-work/
model: access

submodels:
    - name: atmosphere
      model: um
      ncpus: 192
      exe: /g/data/access/payu/access-esm/bin/coe/8.2ka/um_hg3.exe
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/atmosphere
        - /g/data/access/payu/access-esm/input/pre-industrial/start_dump

    - name: ocean
      model: mom
      ncpus: 180
      exe: /g/data/access/payu/access-esm-pmip/pmip-mh/bin/mom5xx
      input:
        - /g/data/ob22/yd3797/access-esm/input
        - /g/data/access/payu/access-esm/input/pre-industrial/ocean/common
        - /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial

    - name: ice
      model: cice
      ncpus: 12
      exe: /g/data/access/payu/access-esm-pmip/pmip-mh/bin/cicexx
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/ice

    - name: coupler
      model: oasis
      ncpus: 0
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/coupler

collate:
   exe: /g/data/access/payu/access-esm/bin/mppnccombine
   restart: true
   mem: 4GB

restart: /g/data/ob22/yd3797/access-esm/esm-mh/archive/restart300

calendar:
    start:
        year: 101
        month: 1
        days: 1

    runtime:
        years: 1
        months: 0
        days: 0

runspersub: 1

stacksize: unlimited

qsub_flags: -W umask=027

storage:
      gdata:
            - ob22
