format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /scratch/w35/hxw599/access-esm/pmip-lm/build/bin/um_hg3.exe
  hashes:
    binhash: 43df7e161b7f2ab6a5dd9262798992c0
    md5: 54bcb5d33e1d69dd8e807b97519de2d6
work/ice/cicexx:
  fullpath: /g/data/access/payu/access-esm/bin/coe/cicexx
  hashes:
    binhash: 612c5f22405c074531e5d415bdc32a02
    md5: 2d8befa0957c1196f8ba387f36b7c1ef
work/ocean/mom5xx:
  fullpath: /g/data/access/payu/access-esm/bin/coe/mom5xx
  hashes:
    binhash: 892a661fe3c35d2e7add6b2fbf041984
    md5: 9b3592016605846dfda306a81ed9579c
