format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/atmosphere/restart_dump.astart
  hashes:
    binhash: 9098654a9691597cb2e32b2ec3a3ff3c
    md5: a94a830f2dc2039205b4e7fe4fc4e47e
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/coupler/a2i.nc
  hashes:
    binhash: 0d3ad31816cbab9f613b4eb70022cc58
    md5: e73f1c10145ed73611711e3d72b46ccf
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/coupler/i2a.nc
  hashes:
    binhash: 07b11bdf0d328ff650380c9e813a3998
    md5: ee971afd752cb3c7dd88619decafbb06
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/coupler/o2i.nc
  hashes:
    binhash: 200e0d7638b9be8e45e0e70ac369aeef
    md5: bcf389266dade59892ecc8945b3d8f94
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ice/cice_in.nml
  hashes:
    binhash: 06933c9973289560f7557a83cac66a19
    md5: 1576287c82da88ffc4752430100f848e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ice/ice.restart_file
  hashes:
    binhash: 24c8818a82045a2afbfd479f89d233a6
    md5: 2b5dc4ee12a95177f5824e43f4cc6e59
work/ice/RESTART/iced.08500101:
  copy: true
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ice/iced.08500101
  hashes:
    binhash: bc9c2fc2b40f7c14989f318e11c59957
    md5: 1020048c002f1a9c0faabc1e804be383
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ice/input_ice.nml
  hashes:
    binhash: ddfd47e7ce36e190053709a84d9452c2
    md5: e2d6d0541795dd3eeae54cda28ecba96
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ice/mice.nc
  hashes:
    binhash: a5bbbec901716eccca5261999b9a9bb6
    md5: 9bf2afcb6d4d6f32bb4c81e7ba99cfce
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 8c52ec8900a26705eb0e00832b2b9eef
    md5: 310e9c9bb52937e03abf795c38b7a36b
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 31f0f71329de130985a3b47e0d2d9906
    md5: 8e5af78a8db7f9b30d64f97c3b9386d4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_age.res.nc
  hashes:
    binhash: b72d8ce12affacdb34a96f6d7cee1d5e
    md5: 1b8b06c6d73ebacaf05f734a44c74d85
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 969354a8989d08917f681a9e569141fd
    md5: 3c3c5eda423bd8be4ee432dcc0dd4547
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cce03d39937cacc02f2b50a0bff33ee6
    md5: ac8d56ee82d482ca3247e69c466d56fe
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_density.res.nc
  hashes:
    binhash: 17c1ad0de82128273066964129fc5e14
    md5: bc1776f39d37b085152b45b394253176
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e60ca43afa53b9868b90b615d727b581
    md5: 1a975ec0348f124cdf853226af2367b3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a57061b7d0f7345f9456f5a66c2d5362
    md5: a6de0392660c9413c45344d21ee04228
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4f41fbb56f28925204a2bb2197f5f27f
    md5: 791f80a05016f69e36a7773b93fa21b3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cb7aeb585205eda8b703dd12bd29ff4c
    md5: 3aeeb10cd63a76bbb2302ec1649185ff
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 87f174cfbff96b91d0816b47a235089f
    md5: c943a7df41dca66ef5a7c28ae8f55489
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1ddc5093cd55241f33dc2cd2fe1a439b
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_solo.res
  hashes:
    binhash: c278e36f2dd61fba9d194ef66158d6a4
    md5: 790f843ba54dbb703dc7f642a216913a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 42ba3f250f961948fcb6a94a353b5153
    md5: c01fcdbef0c2b5f13ae9cba6847d94e9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d126f0c5dedc9b498efbf7b0ed3362b3
    md5: 2924e1523768c38ef3c1cda5ce2618ad
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_tracer.res
  hashes:
    binhash: 4c73e641f0cf5c9585b6d1cdfb9211e4
    md5: 0d2f06b67fc2eeaabe31cb4e943f3f2c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2feba74040b42fb9fa91c431d4a4d780
    md5: d20de7147ba4d76bfedbf8c2b28953d4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/access/payu/access-esm/restart/pmip-lm/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9da5aa59c45ff7803dd77e215c295b32
    md5: 5606ffba46cf7ed4d21a81b3e7fa38a8
